[env:BOARD_VIEWE_ESP32_C3_MD50E]
board = BOARD_VIEWE_ESP32_C3_MD50E
framework = arduino
; The `espressif32` latest official version does not support Arduino v3.1.x, temporarily using a third-party version
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip
upload_speed = 921600
monitor_speed = 115200
build_flags =
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
	-DUSER_SETUP_LOADED
	-include src/User_Setup.h
	-DLV_DRAW_SW_BLEND_ARM_HELIUM=0
	-DLV_DRAW_SW_BLEND_ARM_NEON=0
	-I src
	-I lib
lib_deps =
    lvgl@9.5
    bodmer/TFT_eSPI@^2.5.43
extra_scripts = pre:pre_build.py
