// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11 -> Migrated to LVGL 9.5
// Project name: 1.28-v8-240-240

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"

static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////

typedef enum {
    KNOB_LEFT = 0,                     /*!< EVENT: Rotate to the left */
    KNOB_RIGHT,                        /*!< EVENT: Rotate to the right */
    KNOB_H_LIM,                        /*!< EVENT: Count reaches maximum limit */
    KNOB_L_LIM,                        /*!< EVENT: Count reaches the minimum limit */
    KNOB_ZERO,                         /*!< EVENT: Count back to 0 */
    KNOB_EVENT_MAX,                    /*!< EVENT: Number of events */
    KNOB_NONE,                         /*!< EVENT: No event */
} knob_event_t;

typedef enum {
    BUTTON_PRESS_DOWN = 0,
    BUTTON_PRESS_UP,
    BUTTON_PRESS_REPEAT,
    BUTTON_PRESS_REPEAT_DONE,
    BUTTON_SINGLE_CLICK,
    BUTTON_DOUBLE_CLICK,
    BUTTON_MULTIPLE_CLICK,
    BUTTON_LONG_PRESS_START,
    BUTTON_LONG_PRESS_HOLD,
    BUTTON_LONG_PRESS_UP,
    BUTTON_PRESS_END,
    BUTTON_EVENT_MAX,
    BUTTON_NONE_PRESS,
} button_event_t;

// SCREEN: ui_Screen1
lv_obj_t * ui_Screen1;
lv_obj_t * ui_back;
lv_obj_t * ui_background;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Button3;
// CUSTOM VARIABLES


// SCREEN: ui_time
lv_obj_t * ui_time;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES


// SCREEN: ui_working
lv_obj_t * ui_working;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_back[1] = {&ui_img_back111_png};

///////////////////// ANIMATIONS ////////////////////
uint8_t HF_ui_screen_id=1;
uint8_t HF_open=0;
extern  int selected_index;
extern  char * options[];
extern  char * options2[];
extern int options_max_num;
extern int HF_number;
static int8_t index2=1;

static uint8_t HF_index=1;

void   LVGL_knob_event(void *event)
{
    ESP_LOGI(TAG, "HF---Read  %d", (int)(intptr_t)event);
    if(event == (void*)(intptr_t)KNOB_LEFT)
    {
       ESP_LOGI(TAG,"KNOB_LEFT");
       HF_index=1;
       if(HF_ui_screen_id==1)
       {
           index2++;
           if(index2>=7)
               index2=1;
       }
       else if(HF_ui_screen_id==2)
       {
            selected_index++;
            if(selected_index>options_max_num)
                 selected_index=0;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);
       }
    }
    else if(event == (void*)(intptr_t)KNOB_RIGHT)
    {
        ESP_LOGI(TAG,"KNOB_RIGHT");
        HF_index=1;
        if(HF_ui_screen_id==1)
        {
            index2--;
            if(index2<=0)
                index2=6;
        }
        else if(HF_ui_screen_id==2)
        {
            selected_index--;
            if(selected_index<0)
                selected_index=options_max_num;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);
        }
    }
    if(HF_index==1)
    {
        HF_index=0;

        if(index2==1)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        else if(index2==2)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==3)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==4)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==5)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==6)
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
    }
}

void   LVGL_button_event(void *event)
{
    static uint8_t last_event=BUTTON_PRESS_DOWN;
    ESP_LOGI(TAG, "HF---Read  %d", (int)(intptr_t)event);
    if(event == (void*)(intptr_t)BUTTON_LONG_PRESS_START)
    {
        if(HF_ui_screen_id==1)
        {
            HF_ui_screen_id=2;
            HF_index=0;
            last_event=BUTTON_LONG_PRESS_START;
            _ui_screen_change(&ui_time, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
            return;
        }
    }

    if(event == (void*)(intptr_t)BUTTON_SINGLE_CLICK)
    {
        ESP_LOGI(TAG,"BUTTON_PRESS_UP");
        if(last_event==BUTTON_LONG_PRESS_START)
        {
           last_event=BUTTON_SINGLE_CLICK;
           return ;
        }
        else
        {
            if(HF_ui_screen_id==1)
            {
                HF_ui_screen_id=3;
                HF_open=1;
                _ui_screen_change(&ui_working, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
            }
            else if(HF_ui_screen_id==2)
            {
                selected_index = lv_roller_get_selected(ui_Roller1);
                ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
                _ui_label_set_property(ui_Label3, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
                HF_ui_screen_id=1;
                _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
            }
            else if(HF_ui_screen_id==3)
            {
                HF_ui_screen_id=1;
                HF_open=0;
                _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
            }
        }
    }
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_time, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_working, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_display_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_display_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_time_screen_init();
    ui_working_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_screen_load(ui_Screen1);
}