// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11 -> Migrated to LVGL 9.5
// Project name: 1.28-v8-240-240

#ifndef _UI_H
#define _UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

#include "ui_helpers.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_back;
void ui_event_background(lv_event_t * e);
extern lv_obj_t * ui_background;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

// SCREEN: ui_time
void ui_time_screen_init(void);
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Roller1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_working
void ui_working_screen_init(void);
extern lv_obj_t * ui_working;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern const lv_image_dsc_t ui_img_back111_png;
extern const lv_image_dsc_t ui_img_1kaorou_png;
extern const lv_image_dsc_t ui_img_2kaoji_png;
extern const lv_image_dsc_t ui_img_3danta_png;
extern const lv_image_dsc_t ui_img_4pisa_png;
extern const lv_image_dsc_t ui_img_5liupai_png;
extern const lv_image_dsc_t ui_img_6shutiao_png;
extern const lv_image_dsc_t ui_img_1522004715;
extern const lv_image_dsc_t ui_img_start_png;
extern const lv_image_dsc_t ui_img_362584155;
extern const lv_image_dsc_t ui_img_174066631;

extern const lv_image_dsc_t * ui_imgset_back[1];

// FUNCTIONS
void LVGL_knob_event(void *event);
void LVGL_button_event(void *event);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif